[package]
name = "exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
error-chain = "0.12.4"
hyper = "0.14.27"
reqwest = {version="0.11.20",features=["blocking"]}
